[package]
name = "host"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
dotenvy = { workspace = true }
erc20-counter-core = { workspace = true }
erc20-counter-methods = { workspace = true }
log = { workspace = true }
risc0-ethereum-contracts = { workspace = true }
risc0-steel = { workspace = true, features = ["host"] }
risc0-zkvm = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[dev-dependencies]
alloy = { workspace = true, features = ["json", "node-bindings"] }
alloy-primitives = { workspace = true, features = ["getrandom"] }
erc20-counter-core = { workspace = true, features = ["build-contracts"] }
test-log = { workspace = true }

[features]
beacon = []
history = []
