[package]
name = "erc20-counter-host"
version = { workspace = true }
edition = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(no_auth)'] }

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
dotenvy = { workspace = true }
erc20-counter-core = { workspace = true }
erc20-counter-methods = { workspace = true }
log = { workspace = true }
risc0-ethereum-contracts = { workspace = true }
risc0-steel = { workspace = true, features = ["host"] }
risc0-zkvm = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[dev-dependencies]
alloy = { workspace = true, features = ["json", "node-bindings"] }
alloy-primitives = { workspace = true, features = ["getrandom"] }
test-log = { workspace = true }
