[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
libs = ["../../lib"]
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"

evm_version = "paris"

[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"
