[workspace]
resolver = "2"
members = ["common", "l1-to-l2", "l2", "l2-to-l1"]

[profile.release]
debug = 1
lto = true

[workspace.dependencies]
alloy = "2.0"
examples-common = { path = "common" }
risc0-build = { version = "3.0" }
risc0-ethereum-contracts = { version = "3.0" }
risc0-op-steel = { path = "../../crates/op-steel" }
risc0-zkvm = { version = "3.0" }
serde = "1.0"
