// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#![allow(unused_doc_comments)]
#![no_main]

use alloy_primitives::{address, Address};
use alloy_sol_types::sol;
use risc0_steel::{
    ethereum::{EthEvmInput, ETH_MAINNET_CHAIN_SPEC},
    Contract,
};
use risc0_zkvm::guest::env;

risc0_zkvm::guest::entry!(main);

/// Specify the function to call using the [`sol!`] macro.
/// This parses the Solidity syntax to generate a struct that implements the `SolCall` trait.
sol! {
    /// ERC-20 balance function signature.
    interface IERC20 {
        // function balanceOf(address account) external view returns (uint);
         function getRangePricesLP(
            address lpToken,
            address pool,
            address quoteToken
        ) external returns (uint, uint, bool);
    }
}

/// Function to call, implements the `SolCall` trait.
const CALL: IERC20::getRangePricesLPCall = IERC20::getRangePricesLPCall {
    lpToken: address!("64273624eb57c5cA961d366CBF3968e760Bf0452"),
    pool: address!("64273624eb57c5cA961d366CBF3968e760Bf0452"),
    quoteToken: address!("A0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"),
};

/// Address of the deployed contract to call the function on (USDT contract on Sepolia).
const CONTRACT: Address = address!("61F8BE7FD721e80C0249829eaE6f0DAf21bc2CaC");
/// Address of the caller.
const CALLER: Address = address!("91aa2CcE6B22Ec9eCd8A56C830566e67187fe07E");

fn main() {
    // Read the input from the guest environment.
    let input: EthEvmInput = env::read();

    // Converts the input into a `EvmEnv` for execution. It checks that the state matches the state
    // root in the header provided in the input.
    let env = input.into_env(&ETH_MAINNET_CHAIN_SPEC);
    // Commit the block hash and number used when deriving `EvmEnv` to the journal.
    env::commit_slice(&env.commitment().abi_encode());

    // Execute the view call; it returns the result in the type generated by the `sol!` macro.
    let contract = Contract::new(CONTRACT, &env);
    let mut builder = contract.call_builder(&CALL);
    builder.tx.caller = CALLER;
    let returns = builder.call();
    // println!("View call result: {returns}");
    println!("returns: {:?}", returns._0);
    println!("returns: {:?}", returns._1);
    println!("returns: {:?}", returns._2);
}
