name: Testnet

on:
  merge_group:
  pull_request:
    branches: [ main, "release-*" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: 1.88.0
  RISC0_CRATE_VERSION: "3.0.3"
  FOUNDRY_VERSION: v1.3.6

jobs:
  e2e:
    # Skip if the PR is from a fork.
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    name: ${{ matrix.chain }}
    runs-on: [ self-hosted, prod, Linux, cpu ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - chain: mainnet
            rpc_base: https://eth-mainnet.g.alchemy.com/v2/
            beacon_api: https://ethereum-beacon-api.publicnode.com
          - chain: sepolia
            rpc_base: https://eth-mainnet.g.alchemy.com/v2/
            beacon_api: https://ethereum-sepolia-beacon-api.publicnode.com
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: risc0/risc0/.github/actions/rustup@352dea62857ba57331053cd0986a12c1a4708732
      - uses: ./.github/actions/cargo-risczero-install
        with:
          risczero-version: ${{ env.RISC0_CRATE_VERSION }}
          toolchain-version: ${{ env.RISC0_TOOLCHAIN_VERSION }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FOUNDRY_VERSION }}
      - name: Cargo build
        run: cargo build $CARGO_LOCKED --workspace
        working-directory: examples/erc20-counter
      - name: Run tests against RPC
        run: cargo test $CARGO_LOCKED --workspace
        working-directory: examples/erc20-counter
        env:
          ETH_RPC_URL: ${{ matrix.rpc_base }}${{ secrets.ALCHEMY_RISC0_ETH_API_KEY }}
          BEACON_API_URL: ${{ matrix.beacon_api }}
