name: Scheduled

on:
  workflow_dispatch:
  # Run weekly on Monday at 08:00 UTC
  schedule:
    - cron: '0 8 * * 1'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: "1.94.1"
  RISC0_CRATE_VERSION: "3.0.5"
  FOUNDRY_VERSION: "v1.5.1"
  RUST_LOG: "info"

jobs:
  public:
    name: ${{ matrix.chain }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - chain: mainnet
            rpc_base: https://eth-mainnet.g.alchemy.com/v2/
            beacon_api_base: https://eth-mainnetbeacon.g.alchemy.com/v2/
          - chain: sepolia
            rpc_base: https://eth-sepolia.g.alchemy.com/v2/
            beacon_api_base: https://eth-sepoliabeacon.g.alchemy.com/v2/
          # - chain: hoodi
          #   rpc_base: https://eth-hoodi.g.alchemy.com/v2/
          #   beacon_api_base: https://eth-hoodibeacon.g.alchemy.com/v2/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout latest release
        run: |
          # Use gh to get the tag of the release marked "Latest"
          LATEST_TAG=$(gh release view --json tagName --jq .tagName)
          echo "Found latest release tag: $LATEST_TAG"
          git checkout "$LATEST_TAG"
      - uses: risc0/risc0/.github/actions/rustup@352dea62857ba57331053cd0986a12c1a4708732
      - uses: ./.github/actions/cargo-risczero-install
        with:
          risczero-version: ${{ env.RISC0_CRATE_VERSION }}
          toolchain-version: ${{ env.RISC0_TOOLCHAIN_VERSION }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FOUNDRY_VERSION }}
      - name: Run tests against RPC
        run: cargo test --workspace
        working-directory: examples/erc20-counter
        env:
          ETH_RPC_URL: ${{ matrix.rpc_base }}${{ secrets.ALCHEMY_RISC0_ETH_API_KEY }}/
          BEACON_API_URL: ${{ matrix.beacon_api_base }}${{ secrets.ALCHEMY_RISC0_ETH_API_KEY }}/
